package model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * Property Entity
 * @author afany
 */
@Entity
@Table(name = "properties")
public class Property implements Serializable {

    public static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long propertyId;

    @Column(unique = true, nullable = false)
    private String propertyCode;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String location;

    @Column(nullable = false)
    private Double price;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PropertyStatus status = PropertyStatus.AVAILABLE;

    // Rental functionality
    @Column(nullable = false)
    private Boolean availableForRent = false;

    private Double monthlyRentPrice;

    @ManyToOne
    @JoinColumn(name = "listed_by_agent_id", nullable = false)
    private Agent listedBy;

    @OneToMany(mappedBy = "property", cascade = CascadeType.ALL)
    private List<Transaction> transactions;

    // Transient fields for service layer communication
    @Transient
    private String message;

    @Transient
    private String responseStatus;

    public Property() {}

    public Property(Long propertyId, String propertyCode, String name, String location,
                    Double price, Double monthlyRentPrice, Agent listedBy, List<Transaction> transactions) {
        this.propertyId = propertyId;
        this.propertyCode = propertyCode;
        this.name = name;
        this.location = location;
        this.price = price;
        this.monthlyRentPrice = monthlyRentPrice;
        this.listedBy = listedBy;
        this.transactions = transactions;
    }

    @Override
    public String toString() {
        return "Property{" +
                "propertyId=" + propertyId +
                ", propertyCode=" + propertyCode +
                ", name=" + name +
                ", location=" + location +
                ", price=" + price +
                ", status=" + status +
                ", availableForRent=" + availableForRent +
                ", monthlyRentPrice=" + monthlyRentPrice +
                ", listedBy=" + (listedBy != null ? listedBy.getAgentCode() : "null") +
                '}';
    }

    // Getters and Setters
    public Long getPropertyId() {
        return propertyId;
    }

    public void setPropertyId(Long propertyId) {
        this.propertyId = propertyId;
    }

    public String getPropertyCode() {
        return propertyCode;
    }

    public void setPropertyCode(String propertyCode) {
        this.propertyCode = propertyCode;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public PropertyStatus getStatus() {
        return status;
    }

    public void setStatus(PropertyStatus status) {
        this.status = status;
    }

    public Boolean getAvailableForRent() {
        return availableForRent;
    }

    public void setAvailableForRent(Boolean availableForRent) {
        this.availableForRent = availableForRent;
    }

    public Double getMonthlyRentPrice() {
        return monthlyRentPrice;
    }

    public void setMonthlyRentPrice(Double monthlyRentPrice) {
        this.monthlyRentPrice = monthlyRentPrice;
    }

    public Agent getListedBy() {
        return listedBy;
    }

    public void setListedBy(Agent listedBy) {
        this.listedBy = listedBy;
    }

    public List<Transaction> getTransactions() {
        return transactions;
    }

    public void setTransactions(List<Transaction> transactions) {
        this.transactions = transactions;
    }

    // ✅ FIXED: Transient message and status getters/setters for service responses
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    // ✅ FIXED: Properly implemented getResponseStatus() method
    public String getResponseStatus() {
        return responseStatus;
    }

    // ✅ FIXED: Properly implemented setResponseStatus() method
    public void setResponseStatus(String responseStatus) {
        this.responseStatus = responseStatus;
    }

    // Logic for auto-generated code
    @PrePersist
    public void prePersist() {
        // PropertyCode will be generated by DAO after persistence
        if (this.status == null) {
            this.status = PropertyStatus.AVAILABLE;
        }
        if (this.availableForRent == null) {
            this.availableForRent = false;
        }
    }

    @PostPersist
    public void postPersist() {
        // Code generation happens in DAO layer
        if (this.propertyId != null && this.propertyCode == null) {
            this.propertyCode = "ZP" + String.format("%03d", this.propertyId);
        }
    }
}